<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="suite" duration-ms="51469" started-at="2017-08-14T21:06:09Z" finished-at="2017-08-14T21:07:01Z">
    <groups>
    </groups>
    <test name="Login_Windows" duration-ms="51469" started-at="2017-08-14T21:06:09Z" finished-at="2017-08-14T21:07:01Z">
      <class name="com.propertyfinder.automation.propertyfinder.testcases.WindowLogin">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String, java.lang.String, org.testng.ITestContext)[pri:0, instance:com.propertyfinder.automation.propertyfinder.testcases.WindowLogin@54a097cc]" name="setup" is-config="true" duration-ms="22349" started-at="2017-08-15T02:36:09Z" finished-at="2017-08-15T02:36:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[org.testng.TestRunner@740fb309]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Login_MyAccount_Verify_ValidUser()[pri:0, instance:com.propertyfinder.automation.propertyfinder.testcases.WindowLogin@54a097cc]" name="Login_MyAccount_Verify_ValidUser" duration-ms="27171" started-at="2017-08-15T02:36:32Z" finished-at="2017-08-15T02:36:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [355 matching agents found] but found [2068 matching agents found]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [355 matching agents found] but found [2068 matching agents found]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.propertyfinder.automation.propertyfinder.testcases.WindowLogin.Login_MyAccount_Verify_ValidUser(WindowLogin.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_MyAccount_Verify_ValidUser -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.propertyfinder.automation.propertyfinder.testcases.WindowLogin@54a097cc]" name="teardown" is-config="true" duration-ms="1146" started-at="2017-08-15T02:36:59Z" finished-at="2017-08-15T02:37:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.propertyfinder.automation.propertyfinder.testcases.WindowLogin -->
    </test> <!-- Login_Windows -->
  </suite> <!-- suite -->
</testng-results>
